[package]
name = "wcensor"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wcensor"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wcensor"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wcensor"
description = """
Utility to operate files from a command line.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/censor",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wcensor"
path = "rust/impl/censor/lib.rs"

[[bin]]
name = "wcensor"
path = "rust/impl/censor/entry.rs"

[[test]]
name = "censor_test"
path = "rust/test/censor/censor_test.rs"

[[test]]
name = "censor_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "censor_trivial"
# path = "sample/rust/censor_trivial/src/main.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
# werror = { version = "~0.1", path = "../../rust/werror" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
