[package]
name = "is_slice"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/is_slice"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/is_slice"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/is_slice"
description = """
Macro to answer the question: is it a slice?
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

exclude = [ "/tests", "-*" ]
include = [
  "/rust/impl/typing/is_slice_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[lib]
name = "is_slice"
path = "src/typing/is_slice_lib.rs"

[[test]]
name = "is_slice_test"
path = "tests/typing/is_slice_tests.rs"

[[test]]
name = "is_slice_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "is_slice_trivial_sample"
path = "examples/is_slice_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
test_tools = { workspace = true }
smoke_test = { workspace = true }
