[package]
name = "woptions"
version = "0.1.4"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/woptions"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/woptions"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/woptions"
description = """
Mechanism to define map of options for a fuction and its defaults laconically.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

exclude = [ "/tests", "/examples", "-*" ]
include = [
  "/rust/impl/options/front",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[lib]
name = "woptions"
path = "src/options/front/woptions_lib.rs"

[[test]]
name = "woptions_test"
path = "tests/options/woptions_tests.rs"

[[test]]
name = "woptions_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "woptions_trivial_sample"
path = "examples/woptions_trivial_sample/src/main.rs"

[dependencies]
woptions_meta = { workspace = true }
woptions_runtime = { workspace = true }
former = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
