[package]
name = "deterministic_rand"
version = "0.7.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Viktor Dudnik <viktor.d@obox.systems>",
]
license = "MIT"
readme = "readme.md"
documentation = "https://docs.rs/deterministic_rand"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/deterministic_rand"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/deterministic_rand"
description = """
Hierarchical random number generators for concurrent simulations with switchable determinism.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false


[features]
default = [ "enabled", "determinism" ]
full = [ "enabled", "determinism" ]
no_std = []
use_alloc = [ "no_std" ]
enabled = []
determinism = [ "rand_chacha", "rand_seeder", "iter_tools" ]

[dependencies]
mod_interface = { workspace = true, features = [ "default" ] }
iter_tools = { workspace = true, features = [ "default" ], optional = true }
rand = { workspace = true }
rand_chacha = { workspace = true, optional = true }
rand_seeder = { workspace = true, optional = true }
sealed = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true, features = [ "full" ] }
rayon = { workspace = true }

[[example]]
name = "sample_deterministic_rand_trivial"
path = "examples/deterministic_rand_trivial.rs"
