[package]
name = "impls_index"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/impls_index"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/impls_index"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/impls_index"
description = """
Several of macros to put each function under a named macro to index every function in a class.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/meta/impls_index_lib.rs",
  "/rust/impl/meta/impls_index",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]

[lib]
name = "impls_index"
path = "rust/impl/meta/impls_index/front/impls_index_lib.rs"

[[test]]
name = "impls_index_test"
path = "rust/test/meta/impls_index_tests.rs"

[[test]]
name = "impls_index_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "impls_index_trivial_sample"
path = "sample/rust/impls_index_trivial_sample/src/main.rs"
# qqq : xxx : write please # aaa : Dmytro : added

[dependencies]
impls_index_meta = { version = "~0.1", path = "../../rust/impls_index_meta" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
