[package]
name = "data_type"
version = "0.1.7"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/data_type"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/data_type"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/data_type"
description = """
Collection of primal data types.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/dt",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

# = features

[features]

default = [
  "use_std",
  "either",
  "prelude",
  "interval",
  "make",
  "vectorized_from",
  "type_constructor/default",
]
full = [
  "use_std",
  "either",
  "prelude",
  "interval",
  "make",
  "vectorized_from",
  "type_constructor/full",
]
use_std = []
use_alloc = []

prelude = []
interval = [ "winterval", "winterval/use_std" ]
make = [ "type_constructor/make" ]
vectorized_from = [ "type_constructor/vectorized_from" ]

# = entries

[lib]
name = "data_type"
path = "rust/impl/dt/data_type_lib.rs"

[[test]]
name = "data_type_test"
path = "rust/test/dt/data_type_tests.rs"

[[test]]
name = "data_type_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "data_type_trivial_sample"
path = "sample/rust/data_type_trivial_sample/src/main.rs"

[dependencies]
either = { version = "~1.6", optional = true }
type_constructor = { version = "~0.1", path = "../../rust/type_constructor", optional = true }
winterval = { version = "~0.1", path = "../../rust/winterval", optional = true, default-features = false }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
