[package]
name = "fs_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/fs_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/fs_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/fs_tools"
description = """
Tools to manipulate files.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

include = [
  "/rust/impl/test",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "fs_tools"
path = "rust/impl/test/file/fs_tools_lib.rs"

[[test]]
name = "fs_tools_test"
path = "rust/test/file/fs_tools_lib_test.rs"

# [[example]]
# name = "fs_tools_trivial_sample"
# path = "sample/rust/fs_tools_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
