[package]
name = "woptions_runtime"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/woptions_runtime"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/woptions_runtime"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/woptions_runtime"
description = """
Mechanism to define map of options for a fuction and its defaults laconically. Its runtime.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/options/runtime",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]

[lib]
name = "woptions_runtime"
path = "rust/impl/options/runtime/woptions_lib.rs"

[[test]]
name = "options_runtime_test"
path = "rust/test/options/woptions_runtime_tests.rs"

[dependencies]
former = { version = "~0.1", path = "../../rust/former" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
