[package]
name = "mod_interface"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/mod_interface"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/mod_interface"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/mod_interface"
description = """
Protocol of modularity unifying interface of a module.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/meta/mod_interface_lib.rs",
  "/rust/impl/meta/mod_interface/front",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "mod_interface"
path = "rust/impl/meta/mod_interface/front/lib.rs"

[[test]]
name = "mod_interface_test"
path = "rust/test/meta/mod_interface_lib_test.rs"

# [[example]]
# name = "mod_interface_trivial"
# path = "sample/rust/mod_interface_trivial_sample/src/main.rs"

[dependencies]
mod_interface_meta = { version = "~0.1", path = "../../rust/mod_interface_meta" }
mod_interface_runtime = { version = "~0.1", path = "../../rust/mod_interface_runtime" }

[dev-dependencies]
# anyhow = "~1.0"
# meta_tools = { version = "~0.2", path = "../../rust/meta_tools" }
# maplit = "~1.0"
# trybuild = { version = "~1.0", features = [ "diff" ] }
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
# rustversion = "~1.0"
# xxx : review dependency of former / options
