[package]
name = "mod_interface"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/mod_interface"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/mod_interface"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/mod_interface"
description = """
Protocol of modularity unifying interface of a module.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/meta/mod_interface_lib.rs",
  "/rust/impl/meta/mod_interface/front",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]
use_std = []
use_alloc = []

[lib]
name = "mod_interface"
path = "rust/impl/meta/mod_interface/front/mod_interface_lib.rs"

[[test]]
name = "mod_interface_test"
path = "rust/test/meta/mod_interface_tests.rs"

[[test]]
name = "mod_interface_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "mod_interface_trivial_sample"
path = "sample/rust/mod_interface_trivial_sample/src/main.rs"
# zzz : write # aaa : Dmytro : added

[dependencies]
mod_interface_meta = { version = "~0.1", path = "../../rust/mod_interface_meta" }
mod_interface_runtime = { version = "~0.1", path = "../../rust/mod_interface_runtime" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
# xxx : review dependency of former / options
