[package]
name = "wtest"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtest"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest"
description = """
Tools for writing and running tests.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/test",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]

[lib]
name = "wtest"
path = "rust/impl/test/wtest_lib.rs"

[[test]]
name = "wtest_test"
path = "rust/test/test/wtest_lib_test.rs"

[[test]]
name = "wtest_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "wtest_trivial_sample"
path = "sample/rust/wtest_trivial_sample/src/main.rs"

[dependencies]
# paste = "~1.0"
# anyhow = "~1.0"
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
