[package]
name = "wtest"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtest"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/wtest"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/wtest"
description = """
Tools for writing and running tests.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

include = [
  "/rust/impl/test",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[[bin]]
name = "wtest"
path = "src/test/wtest_entry.rs"

[lib]
name = "wtest"
path = "src/test/wtest_lib.rs"

[[test]]
name = "wtest_test"
path = "tests/test/wtest_tests.rs"

[[test]]
name = "wtest_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "wtest_trivial_sample"
path = "examples/wtest_trivial_sample/src/main.rs"

[dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
wtools = { workspace = true }
wca = { workspace = true }
wpublisher = { workspace = true }
anyhow = "~1.0.56"

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
