[package]
name = "data_type_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[features]
type_constructor = []
default = [ "type_constructor" ]

[dependencies]
 data_type = { workspace = true }
