[package]
name = "for_each"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/for_each"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/for_each"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/for_each"
description = """
Apply macro for each element of a list.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/meta/for_each",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]

[lib]
name = "for_each"
path = "rust/impl/meta/for_each/lib.rs"

[[test]]
name = "for_each_test"
path = "rust/test/meta/for_each_lib_test.rs"

[[test]]
name = "for_each_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "for_each_trivial_sample"
path = "sample/rust/for_each_trivial_sample/src/main.rs"

[[example]]
name = "for_each_map_style_sample"
path = "sample/rust/for_each_map_style_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
