[package]
name = "wca_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
wca = { version = "~0.1", path = "../../../module/rust_move/wca" }
wstring_tools = { version = "~0.1", path = "../../../module/rust/wstring_tools" }
# wca = "*"
