[package]
name = "fs_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/fs_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/fs_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/fs_tools"
description = """
Tools to manipulate files.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
exclude = [ "/tests", "/examples", "-*" ]
include = [
  "/rust/impl/fs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "enabled" ]
full = [ "enabled" ]
# use_std = []
no_std = []
use_alloc = []
enabled = []

[lib]
name = "fs_tools"
path = "src/fs/fs_tools_lib.rs"

[[test]]
name = "fs_tools_test"
path = "tests/fs/fs_tools_tests.rs"

[[test]]
name = "fs_tools_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "fs_tools_trivial_sample"
path = "examples/fs_tools_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { workspace = true }
# smoke_test = { workspace = true }
