[package]
name = "werror"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/werror"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/werror"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/werror"
description = """
Basic exceptions handling mechanism.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/error",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "werror"
path = "rust/impl/error/lib.rs"

[[test]]
name = "error_test"
path = "rust/test/error/lib_test.rs"

[[test]]
name = "werror_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "error_trivial"
path = "sample/rust/error_trivial/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
