[package]
name = "proc_macro_tools_trivial_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# proc_macro_tools = "*"
syn = { version = "~1.0", features = [ "full", "extra-traits", "parsing" ] }
quote = "~1.0"
