[package]
name = "test_tools"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/test_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/test_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/test_tools"
description = """
Tools for writing and running tests.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

include = [
  "/rust/impl/test",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "test_tools"
path = "rust/impl/test/test_tools_lib.rs"

[[test]]
name = "test_tools_test"
path = "rust/test/test/test_tools_lib_test.rs"

# zzz : add sample
# [[example]]
# name = "test_tools_trivial"
# path = "sample/rust/test_tools_trivial/src/main.rs"

[dependencies]
# paste = "~1.0"
# anyhow = "~1.0"
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
