[package]
name = "woptions"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/woptions"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/woptions"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/woptions"
description = """
Mechanism to define map of options for a fuction and its defaults laconically.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/options/front",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]

[lib]
name = "woptions"
path = "rust/impl/options/front/lib.rs"

[[test]]
name = "woptions_test"
path = "rust/test/options/woptions_lib_test.rs"

[[test]]
name = "woptions_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "woptions_trivial"
path = "sample/rust/woptions_trivial/src/main.rs"

[dependencies]
woptions_meta = { version = "~0.1", path = "../../rust/woptions_meta" }
woptions_runtime = { version = "~0.1", path = "../../rust/woptions_runtime" }
former = { version = "~0.1", path = "../../rust/former" }
# meta_tools_min = { version = "~0.2", path = "../../rust/meta_tools_min" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
