[package]
name = "wtools"
version = "0.1.9"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtools"
description = """
Collection of general purpose tools for solving problems. Fundamentally extend the language without spoiling, so may be used solely or in conjunction with another module of such kind.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/wtools_lib.rs",
  "/rust/impl/meta/mod.rs",
  "/rust/impl/typing/mod.rs",
  "/rust/impl/convert/mod.rs",
  "/rust/impl/time/mod.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtools"
path = "rust/impl/wtools_lib.rs"

[[test]]
name = "wtools_test"
path = "rust/test/wtools_lib_test.rs"

[[example]]
name = "wtools_trivial"
path = "sample/rust/wtools_trivial/src/main.rs"

[features]
in_wtools = []
nightly = [ "typing_tools/nightly" ]
default = [ "in_wtools" ]

[package.metadata.docs.rs]
all-features = true
# rustdoc-args = []

[dependencies]
former = { version = "~0.1", path = "../../rust/former" }
woptions = { version = "~0.1", path = "../../rust/woptions" }
meta_tools = { version = "~0.1", path = "../../rust/meta_tools" }
typing_tools = { version = "~0.1", path = "../../rust/typing_tools" }
time_tools = { version = "~0.1", path = "../../rust/time_tools" }
wstring_tools = { version = "~0.1", path = "../../rust/wstring_tools" }
werror = { version = "~0.1", path = "../../rust/werror" }
winterval = { version = "~0.1", path = "../../rust/winterval" }
parse-display = { version = "~0.5" } # xxx : add test? # xxx : move

[dev-dependencies]
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }
# trybuild = { version = "~1.0", features = [ "diff" ] }
# anyhow = "~1.0"
rustversion = "~1.0"
