[package]
name = "wtest"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wtest"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wtest"
description = """
Tools for writing and running tests.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

include = [
  "/rust/impl/test",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wtest"
path = "rust/impl/test/lib.rs"

[[test]]
name = "wtest_test"
path = "rust/test/test/wtest_lib_test.rs"

[[example]]
name = "wtest_trivial_sample"
path = "sample/rust/wtest_trivial_sample/src/main.rs"

[dependencies]
# paste = "~1.0"
# anyhow = "~1.0"
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
