[package]
name = "time_tools"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/time_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/time_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/time_tools"
description = """
Collection of general purpose time tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/time",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [
  "use_std",
  "now",
]
full = [
  "use_std",
  "use_alloc",
  "now",
]
use_std = []
use_alloc = []

now = [ "use_std", "chrono", "chrono/default" ]

[lib]
name = "time_tools"
path = "rust/impl/time/time_tools_lib.rs"

[[test]]
name = "time_tools_test"
path = "rust/test/time/tests.rs"

[[test]]
name = "time_tools_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "time_tools_trivial_sample"
path = "sample/rust/time_tools_trivial_sample/src/main.rs"

[dependencies]
chrono = { version = "~0.4", optional = true, default-features = false }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }

