[package]
name = "time_tools"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/time_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/time_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/time_tools"
description = """
Collection of general purpose time tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/time",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "time_tools"
path = "rust/impl/time/lib.rs"

[[test]]
name = "time_tools_test"
path = "rust/test/time/lib_test.rs"

[[example]]
name = "time_tools_trivial"
path = "sample/rust/time_tools_trivial/src/main.rs"

[dependencies]
chrono = "~0.4"

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
