[package]
name = "component_model_meta"
version = "0.10.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "readme.md"
documentation = "https://docs.rs/component_model_meta"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/component_model_meta"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/component_model_meta"
description = """
A flexible implementation of the Builder pattern supporting nested builders and collection-specific subcomponent_models. Implementation of its derive macro. Should not be used independently, instead use module::component_model which relies on the module.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[lib]
proc-macro = true

[features]

default = [ "enabled", "full" ]
full = [
  "enabled",

  "derive_component_model",
  "derive_components",
  "derive_component_from",
  "derive_component_assign",
  "derive_components_assign",
  "derive_from_components",
]
enabled = [ "macro_tools/enabled", "component_model_types/enabled" ]

derive_component_model = [ "convert_case" ]
derive_components = [ "derive_component_assign", "derive_components_assign", "derive_component_from", "derive_from_components" ]
derive_component_assign = []
derive_components_assign = [ "derive_component_assign", "convert_case" ]
derive_component_from = []
derive_from_components = []

[dependencies]
macro_tools = { workspace = true, features = [ "attr", "diag", "item_struct" ], optional = true } # Optimized feature set based on actual usage
component_model_types = { workspace = true, features = [ "types_component_assign" ], optional = true }
convert_case = { version = "0.6.0", default-features = false, optional = true, features = [] }

[dev-dependencies]
test_tools = { workspace = true, features = [ "full" ] }
