[package]
name = "template_alias"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/template_alias"
repository = "https://github.com/Wandalen/wTools/tree/master/module/alias/template_alias"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/alias/template_alias"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "template_alias"
path = "rust/impl/_blank/standard_lib.rs"

[[test]]
name = "template_alias_test"
path = "rust/test/template_alias/lib_test.rs"

[[test]]
name = "template_alias_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
