[package]
name = "proc_macro_tools"
version = "0.1.4"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/proc_macro_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/proc_macro_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/proc_macro_tools"
description = """
Tools for writing procedural macroses.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/proc_macro",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]

[lib]
name = "proc_macro_tools"
path = "rust/impl/proc_macro/lib.rs"

[[test]]
name = "proc_macro_tools_test"
path = "rust/test/proc_macro/proc_macro_tools_lib_test.rs"

[[test]]
name = "proc_macro_tools_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "proc_macro_trivial_sample"
path = "sample/rust/proc_macro_tools_trivial/src/main.rs"
# qqq : for Dima : normalize names of samples, missing postfix _sample

[dependencies]
proc-macro2 = { version = "~1.0", features = [] }
quote = { version = "~1.0", features = [] }
syn = { version = "~1.0", features = [ "full", "extra-traits" ] }
winterval = { version = "~0.1", path = "../../rust/winterval" }
type_constructor = { version = "~0.1", path = "../../rust/type_constructor" }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
