[package]
name = "former"
version = "0.1.11"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former"
description = """
Former - variation of builder pattern.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/former/front",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]
full = []

[lib]
name = "former"
path = "rust/impl/former/front/lib.rs"

[[test]]
name = "former_test"
path = "rust/test/former/former_front_tests.rs"

[[test]]
name = "former_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "former_trivial"
path = "sample/rust/former_trivial/src/main.rs"

[dependencies]
former_meta = { version = "~0.1", path = "../../rust/former_meta" }
former_runtime = { version = "~0.1", path = "../../rust/former_runtime" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
# meta_tools_min = { version = "~0.2", path = "../../rust/meta_tools_min" }
