[package]
name = "diagnostics_tools"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/diagnostics_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/diagnostics_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/diagnostics_tools"
description = """
Diagnostics tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/diagnostics",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "diagnostics_tools"
path = "rust/impl/diagnostics/lib.rs"

[[test]]
name = "diagnostics_tools_test"
path = "rust/test/diagnostics/lib_test.rs"

# [[example]]
# name = "diagnostics_tools_trivial"
# path = "sample/rust/diagnostics_tools_trivial/src/main.rs"
# zzz : xxx : implement

[features]
default = [ "runtime_assertions", "compiletime_assertions" ]
all = [ "runtime_assertions", "compiletime_assertions" ]
runtime_assertions = [ "pretty_assertions" ] # run-time assertions
compiletime_assertions = [] # compile-time assertions

[package.metadata.docs.rs]
all-features = true

[dependencies]
pretty_assertions = { version = "~1.2", optional = true }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
