[package]
name = "woptions_meta"
version = "0.1.4"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/woptions_meta"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/woptions_meta"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/woptions_meta"
description = """
Mechanism to define map of options for a fuction and its defaults laconically. Its meta.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/options/meta",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = []
full = []

[lib]
proc-macro = true
name = "woptions_meta"
path = "src/options/meta/woptions_lib.rs"

[dependencies]
convert_case = "~0.5" # xxx : move to string_tools
proc_macro_tools = { workspace = true }
# meta_tools = { workspace = true }
iter_tools = { workspace = true }
meta_tools = { workspace = true }

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
