[package]
name = "implements"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/implements"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/implements"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/implements"
description = """
Macro to answer the question: does it implement a trait?
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/typing/implements_impl.rs",
  "/rust/impl/typing/implements_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
default = [ "use_std" ]

[lib]
name = "implements"
path = "rust/impl/typing/implements_lib.rs"

[[test]]
name = "implements_test"
path = "rust/test/typing/implements_tests.rs"

[[test]]
name = "implements_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "implements_trivial_sample"
path = "sample/rust/implements_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
# trybuild = { version = "~1.0", features = [ "diff" ] }
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
