[package]
name = "wtest_basic_trivial"
version = "0.0.0"
edition = "2021"
publish = false

[[test]]
name = "trivial_test"
path = "../../tests/trivial_test.rs"

[dependencies]
wtest_basic = { workspace = true }
