[package]
name = "video_experiment"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/video_experiment"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/video_experiment"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/video_experiment"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]
use_std = []
use_alloc = []
mp4_ratio_conversion = []

[lib]
name = "video_experiment"
path = "rust/impl/video/video_experiment_lib.rs"

[[test]]
name = "video_experiment_test"
path = "rust/test/video/video_experiment_tests.rs"

# [[test]]
# name = "video_experiment_smoke_test"
# path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "video_experiment_trivial_sample"
# path = "sample/rust/video_experiment_trivial_sample/src/main.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
gif = "~0.11"
apng = "~0.2.0"
png = "~0.16.3"
ac-ffmpeg = "~0.17"
openh264 = "~0.2"

[dev-dependencies]
image = "~0.24"
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
