[package]
name = "wpublisher"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wpublisher"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wpublisher"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wpublisher"
description = """
Utility to publish modules on `crates.io` from a command line.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/publisher",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[[bin]]
name = "wpublisher"
path = "rust/impl/publisher/entry.rs"

[[test]]
name = "publisher_test"
path = "rust/test/publisher/mod.rs"

[[test]]
name = "publisher_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "publisher_trivial"
# path = "sample/rust/publisher_trivial/src/main.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
wca = { version = "~0.1", path = "../../move/wca" }
anyhow = "1.0.56"
toml_edit = "0.14.2"
cargo_metadata = "0.14.2"
ureq = "2.4.0"
sha-1 = "0.10.0"
globwalk = "0.8.1"

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
