[package]
name = "wpublisher"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wpublisher"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/wpublisher"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/wpublisher"
description = """
Utility to publish modules on `crates.io` from a command line.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/publisher",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[lib]
name = "wpublisher"
path = "src/publisher/wpublisher_lib.rs"

[[bin]]
name = "wpublisher"
path = "src/publisher/wpublisher_entry.rs"

[[test]]
name = "publisher_test"
path = "tests/publisher/wpublisher_tests.rs"

[[test]]
name = "publisher_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "wpublisher_trivial_sample"
path = "examples/wpublisher_trivial_sample/src/main.rs"

[dependencies]
wtools = { workspace = true }
wca = { workspace = true }
anyhow = "~1.0"
toml_edit = "~0.14"
cargo_metadata = "~0.14"
ureq = "~2.4"
sha-1 = "~0.10"
globwalk = "~0.8"
petgraph = "~0.6"

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }

