[package]
name = "type_constructor__parametrized_element_sample"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
type_constructor = { version = "*", path = "../../../module/rust/type_constructor" }
