[package]
name = "automata_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/automata_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/automata_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/automata_tools"
description = """
Automata tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/automata",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "automata_tools"
path = "rust/impl/automata/automata_tools_lib.rs"

[[test]]
name = "automata_tools_test"
path = "rust/test/automata/automata_tools_lib_test.rs"

# [[example]]
# name = "automata_trivial_sample"
# path = "sample/rust/automata_trivial_sample/src/main.rs"
# zzz : write please

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools", features = [] }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
