[package]
name = "former_runtime"
version = "0.1.10"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/former_runtime"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/former_runtime"
description = """
Former - variation of builder pattern. Its runtime.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

include = [
  "/rust/impl/former/runtime",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "former_runtime"
path = "rust/impl/former/runtime/lib.rs"

[[test]]
name = "former_runtime_test"
path = "rust/test/former/former_runtime_lib_test.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
meta_tools = { version = "~0.2", path = "../../rust/meta_tools" }
anyhow = "~1.0"
