[package]
name = "wstring_tools"
version = "0.1.1"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wstring_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/wstring_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/wstring_tools"
description = """
String tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/string",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
indentation = []
parse  = [ "split" ]
split = []
default = [ "indentation", "parse", "split" ]
full = [ "indentation", "parse", "split" ]

[lib]
name = "wstring_tools"
path = "rust/impl/string/wstring_tools_lib.rs"

[[test]]
name = "string_test"
path = "rust/test/string/wstring_tools_lib_test.rs"

[[example]]
name = "wstring_tools_trivial"
path = "sample/rust/wstring_tools_trivial/src/main.rs"
# xxx # aaa : done

[dependencies]
former = { version = "~0.1", path = "../../rust/former" }
# woptions = { version = "~0.1", path = "../../rust/woptions" }
# wtools = { version = "~0.2", path = "../../rust/wtools" }
# werror = { version = "~0.1", path = "../../rust/werror" }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
