[package]
name = "template_blank"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/template_blank"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/template_blank"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/template_blank"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "template_blank"
path = "rust/impl/_blank/standard_lib.rs"

[[test]]
name = "template_blank_test"
path = "rust/test/_blank/lib_test.rs"

# [[test]]
# name = "template_blank_smoke_test"
# path = "rust/test/_integration_test/smoke_test.rs"

# [[example]]
# name = "template_blank_trivial_sample"
# path = "sample/rust/template_blank_trivial_sample/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
