[package]
name = "inspect_type"
version = "0.1.2"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/inspect_type"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/inspect_type"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/inspect_type"
description = """
Diagnostic-purpose tools to inspect type of a variable and its size.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "diagnostic-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/typing/inspect_type_lib.rs",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
use_std = []
use_alloc = []
nightly = []
default = [ "use_std" ]

[lib]
name = "inspect_type"
path = "rust/impl/typing/inspect_type_lib.rs"

[[test]]
name = "inspect_type_test"
path = "rust/test/typing/inspect_type_tests.rs"

[[test]]
name = "inspect_type_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "inspect_type_trivial"
path = "sample/rust/inspect_type_trivial/src/main.rs"

[dependencies]

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
# rustversion = "~1.0"
