[package]
name = "iter_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/iter_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/iter_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/iter_tools"
description = """
Collection of general purpose tools to iterate. Currently it simply reexport itertools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

include = [
  "/rust/impl/iter",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "iter_tools"
path = "rust/impl/iter/lib.rs"

[[test]]
name = "iter_tools_test"
path = "rust/test/iter/lib_test.rs"

# [[example]]
# name = "iter_tools_trivial"
# path = "sample/rust/iter_tools_trivial/src/main.rs"
# qqq : for Rust dev : please add

[dependencies]
itertools = "~0.10.3"

[dev-dependencies]
wtest_basic = { version = "~0.1", path = "../wtest_basic" }
