[package]
name = "mod_interface_with_debug_sample"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "mod_interface_trivial_sample"
path = "src/main.rs"

[dependencies]
mod_interface = { version = "*", path = "../../../module/rust/mod_interface" }
