[package]
name = "impls_index"
version = "0.1.4"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/impls_index"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/impls_index"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/impls_index"
description = """
Several of macros to put each function under a named macro to index every function in a class.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/meta/impls_index_lib.rs",
  "/rust/impl/meta/impls_index",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ ]
full = []
# use_std = []
no_std = []
use_alloc = []

[lib]
name = "impls_index"
path = "src/meta/impls_index/front/impls_index_lib.rs"

[[test]]
name = "impls_index_test"
path = "tests/meta/impls_index_tests.rs"

[[test]]
name = "impls_index_smoke_test"
path = "tests/_integration_test/smoke_test.rs"

[[example]]
name = "impls_index_trivial_sample"
path = "examples/impls_index_trivial_sample/src/main.rs"
# aaa : xxx : write please # aaa : Dmytro : added

[dependencies]
impls_index_meta = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
smoke_test = { workspace = true }
