[package]
name = "willbe_old"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/willbe"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/willbe_old"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/willbe_old"
description = """
___
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]
publish = false

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/willbe_old",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "use_std" ]
full = [ "use_std", "use_alloc" ]
use_std = []
use_alloc = []

[lib]
name = "willbe_old"
path = "rust/impl/willbe_old/willbe_lib.rs"

[[bin]]
name = "willbe_old"
path = "rust/impl/willbe_old/willbe_entry.rs"

[[test]]
name = "willbe_test"
path = "rust/test/willbe_old/willbe_test.rs"

# disable for now
# [[test]]
# name = "willbe_smoke_test"
# path = "rust/test/_integration_test/smoke_test.rs"
#
# [[example]]
# name = "willbe_trivial_sample"
# path = "sample/rust/willbe_trivial_sample/src/main.rs"

[dependencies]
wtools = { version = "~0.2", path = "../../rust/wtools" }
wca = { version = "~0.1", path = "../../move/wca" }
toml = "0.5"
globwalk = "0.8"
cargo_metadata = "0.15"
path-absolutize = "3"
petgraph = "~0.6"
rand = "0.8.4"

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
tempfile = "3"
assert_cmd = "2.0"
predicates = "2.1"
