[package]
name = "wca"
version = "0.1.0"
edition = "2018"
authors = ["Kostiantyn Wandalen <wandalen@obox.systems>", "Volodymyr M. <volodymyr.migdal@gmail.com>", "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>" ]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/wca"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust_move/wca"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust_move/wca/Readme.md"
description = """
The tool to make CLI ( commands user interface ). It is able to aggregate external binary applications, as well as functions, which are written in your language.
"""
categories = [ "command-line-interface", "command-line-utilities" ]
keywords = [ "wtools", "CLI", "CUI", "user-interface" ]

include = [
  "/rust/impl/ca",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[lib]
name = "wca"
path = "rust/impl/ca/mod.rs"

[[test]]
name = "wca_test"
path = "rust/test/ca/mod.rs"

[dependencies]
wtools = { version = "~0.1", path = "../../rust/wtools" }
former = { version = "~0.1", path = "../../rust/former" }
wstring_tools = { version = "~0.1", path = "../../rust/wstring_tools" }
maplit = "1.0.2"

[dev-dependencies]
wtest_basic = { version = "~0.1", path = "../../rust/wtest_basic" }
