name : include_md

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # include_md

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/move/include_md/Cargo.toml'
      module_name : 'include_md'
      commit_message : ${{ github.event.head_commit.message }}
