name : graph_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # graph_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/move/graph_tools/Cargo.toml'
      module_name : 'graph_tools'
