name : typing_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # typing_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/typing_tools/Cargo.toml'
      module_name : 'typing_tools'
      commit_message : ${{ github.event.head_commit.message }}
