name : implements

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # implements

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/implements/Cargo.toml'
      module_name : 'implements'
      commit_message : ${{ github.event.head_commit.message }}

  # instance_of

  test_instance_of :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/alias/instance_of/Cargo.toml'
      module_name : 'instance_of'
      commit_message : ${{ github.event.head_commit.message }}
