name : wtest_basic

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # wtest_basic

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/wtest_basic/Cargo.toml'
      module_name : 'wtest_basic'
      commit_message : ${{ github.event.head_commit.message }}
