name : wlang

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/move/wlang/Cargo.toml'
      module_name : 'wlang'
      commit_message : ${{ github.event.head_commit.message }}
