name : unitore

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # unitore

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/move/unitore/Cargo.toml'
      module_path: 'module/move/unitore/'
      module_name : 'unitore'
      commit_message : ${{ github.event.head_commit.message }}
