name : mod_interface

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # mod_interface

  test_mod_interface :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/mod_interface/Cargo.toml'
      module_name : 'mod_interface'
      commit_message : ${{ github.event.head_commit.message }}

  # mod_interface_meta

  test_mod_interface_meta :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/mod_interface_meta/Cargo.toml'
      module_name : 'mod_interface_meta'
      commit_message : ${{ github.event.head_commit.message }}

  # mod_interface_runtime

  # test_mod_interface_runtime :
  #   uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
  #   with :
  #     manifest_path : 'module/rust/mod_interface_runtime/Cargo.toml'
  #     module_name : 'mod_interface_runtime'
  #     commit_message : ${{ github.event.head_commit.message }}

  # multilayer

  test_multilayer :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/multilayer/Cargo.toml'
      module_name : 'multilayer'
      commit_message : ${{ github.event.head_commit.message }}
