name : wproc_macro

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # wproc_macro

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/wproc_macro/Cargo.toml'
      module_name : 'wproc_macro'
      commit_message : ${{ github.event.head_commit.message }}
