name : impls_index

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # impls_index

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/impls_index/Cargo.toml'
      module_name : 'impls_index'
      commit_message : ${{ github.event.head_commit.message }}

  # impls_index_meta

  test_impls_index_meta :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/impls_index_meta/Cargo.toml'
      module_name : 'impls_index_meta'
      commit_message : ${{ github.event.head_commit.message }}
