name : mod_interface

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # mod_interface

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/mod_interface/Cargo.toml'
      module_name : 'mod_interface'

  # mod_interface_meta

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/mod_interface_meta/Cargo.toml'
      module_name : 'mod_interface_meta'

  # mod_interface_runtime

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/mod_interface_runtime/Cargo.toml'
      module_name : 'mod_interface_runtime'
