name : reflect_tools_meta

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # reflect_tools_meta

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/reflect_tools_meta/Cargo.toml'
      module_path: 'module/core/reflect_tools_meta/'
      module_name : 'reflect_tools_meta'
      commit_message : ${{ github.event.head_commit.message }}
