name : graphs_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # graphs_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/move/graphs_tools/Cargo.toml'
      module_path: 'module/move/graphs_tools/'
      module_name : 'graphs_tools'
      commit_message : ${{ github.event.head_commit.message }}
