name : impls_index

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # impls_index

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/impls_index/Cargo.toml'
      module_name : 'impls_index'

  # impls_index_meta

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/impls_index_meta/Cargo.toml'
      module_name : 'impls_index_meta'
