name : werror

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # werror

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/werror/Cargo.toml'
      module_name : 'werror'
      commit_message : ${{ github.event.head_commit.message }}
