name : wautomata

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # wautomata

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/wautomata/Cargo.toml'
      module_name : 'wautomata'
      commit_message : ${{ github.event.head_commit.message }}
