name : clone_dyn

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # clone_dyn

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/clone_dyn/Cargo.toml'
      module_name : 'clone_dyn'
      commit_message : ${{ github.event.head_commit.message }}
