name : non_std

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # non_std

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/non_std/Cargo.toml'
      module_path: 'module/alias/non_std/'
      module_name : 'non_std'
      commit_message : ${{ github.event.head_commit.message }}
