name : winterval

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # winterval

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/winterval/Cargo.toml'
      module_name : 'winterval'
      commit_message : ${{ github.event.head_commit.message }}
