name : test_experimental_a

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # test_experimental_a

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/test/a/Cargo.toml'
      module_name : 'test_experimental_a'
      commit_message : ${{ github.event.head_commit.message }}
