name : wstring_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # wstring_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/wstring_tools/Cargo.toml'
      module_name : 'wstring_tools'
      commit_message : ${{ github.event.head_commit.message }}
