name : image_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # image_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/blank/image_tools/Cargo.toml'
      module_name : 'image_tools'
      commit_message : ${{ github.event.head_commit.message }}
