name : reflect_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # reflect_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/reflect_tools/Cargo.toml'
      module_path: 'module/core/reflect_tools/'
      module_name : 'reflect_tools'
      commit_message : ${{ github.event.head_commit.message }}
