name : wstring_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # string_tools

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/rust/wstring_tools/Cargo.toml'
      module_name : 'string_tools'
