[package]
name = "meta_tools"
version = "0.2.12"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Volodymyr M. <volodymyr.migdal@gmail.com>",
  "Dmytro Kryvoruchko <dm.vict.kr@gmail.com>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/meta_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/rust/meta_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/rust/meta_tools"
description = """
Collection of general purpose meta tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[package.metadata.docs.rs]
all-features = true

include = [
  "/rust/impl/meta",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [
  "for_each",
  "impls_index",
  "mod_interface",
  "former",
  "options",
  "collection_make",
  "use_std",
]
full = [
  "for_each",
  "impls_index",
  "mod_interface",
  "former",
  "options",
  "collection_make",
  "use_std",
  "use_alloc",
]
use_std = []
use_alloc = []

collection_make = [ "literally" ]
options = [ "woptions" ]

[lib]
name = "meta_tools"
path = "rust/impl/meta/meta_tools_lib.rs"

[[test]]
name = "meta_tools_test"
path = "rust/test/meta/meta_tools_tests.rs"

[[test]]
name = "meta_tools_smoke_test"
path = "rust/test/_integration_test/smoke_test.rs"

[[example]]
name = "meta_tools_trivial_sample"
path = "sample/rust/meta_tools_trivial_sample/src/main.rs"
# qqq : for Rust dev : add a sample with impls + index. discuss first
# - all samples should be in md files and have short descriptions

[dependencies]
for_each = { version = "~0.1", path = "../../rust/for_each", optional = true, default-features = false }
impls_index = { version = "~0.1", path = "../../rust/impls_index", optional = true, default-features = false }
mod_interface = { version = "~0.1", path = "../../rust/mod_interface", optional = true, default-features = false }
former = { version = "~0.1", path = "../../rust/former", optional = true, default-features = false }
woptions = { version = "~0.1", path = "../../rust/woptions", optional = true, default-features = false }
literally = { version = "~0.1", optional = true, default-features = false }

[dev-dependencies]
test_tools = { version = "~0.1", path = "../../rust/test_tools" }
